//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginacionWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUGARES
    {
        public int id_lugarVisita { get; set; }
        public string nombre_lugarVisita { get; set; }
        public string direccion_lugarVisita { get; set; }
    }
}
